### ISSUE TITLE
[epic] Contract Reviews

### ISSUE THREAD

**Issue by shorn-gnosis** [aboutcircles/circles-contracts-v2#18]
- [x] internal contracts review
 - [x] bring v2 (contracts and SDK) to hackers to gather feedback
 - [x] #27
 - [x] address findings from dev community feedback

**Comment by benjaminbollen** [comment]
completed Hats open review
