### ISSUE TITLE
[epic] Patching v1.0.0-beta 🐛

### ISSUE THREAD

**Issue by benjaminbollen** [aboutcircles/circles-contracts-v2#79]
- [ ] patch the birthday bug
- [ ] correct the `stopped()` function
- [ ] evaluate remedies for `stopped()` in `v1.0.0-beta`: Merkle-proof or zk-coprocessor proofs of last mint
- [ ] make last mint time publicly readable
- [ ] evaluate and plan constraints on human vs group registration (wrt v1)
    - [ ] wider discussion: should we keep `custom treasury` ?
    - [ ] wider discussion: should not introduce a DAG for group collateral ?
- [ ] use create2 for deploying vaults and wrapped erc20

**Comment by benjaminbollen** [comment]
@roleengineer I moved this to a new epic #93 because I think that if we propose improvements, we should first setup measurements and CI regression checks, no?
