### ISSUE TITLE
[epic] technical documentation

### ISSUE THREAD

**Issue by benjaminbollen** [aboutcircles/circles-contracts-v2#88]
- [x] #108
- [ ] #89
- [ ] discuss where contract docs should live, and plan what work is needed to improve it (a draft outline exists in the repo)
- [x] #92
- [ ] add natspecs to docs
- [ ] add deployment information (Beta, Rings) to docs
